#!/bin/bash

set -e

export DB_HOST=${DB_HOST:-database}
export DB_PORT=${DB_PORT:-3306}
export DB_JDBC=${DB_JDBC:-mysql}
export DB_SCHEMAS=${DB_SCHEMAS}
export DB_USER=${DB_USER:-root}
export DB_PASSWORD=${DB_PASSWORD:-mysql}
export DB_SQLDIR=${DB_SQLDIR:-/db/}
export FLYWAY_EXTRA=${FLYWAY_EXTRA:-}
export DB_JDBC_URL=${DB_JDBC_URL:-}

export DB_JDBC_URL_TEMPLATE=jdbc:${DB_JDBC}://${DB_HOST}
if [ $DB_JDBC == "oracle" ]; then
	export DB_JDBC_TYPE=${DB_JDBC_TYPE:-thin}
	export DB_JDBC_URL_TEMPLATE=jdbc:${DB_JDBC}:${DB_JDBC_TYPE}:@${DB_HOST}
fi

if [ -n "${DB_SCHEMAS}"  ]; then export FLYWAY_EXTRA="-schemas=${DB_SCHEMAS} $FLYWAY_EXTRA";   fi
if [ -n "${DB_USER}"     ]; then export FLYWAY_EXTRA="-user=${DB_USER} $FLYWAY_EXTRA";         fi
if [ -n "${DB_PASSWORD}" ]; then export FLYWAY_EXTRA="-password=${DB_PASSWORD} $FLYWAY_EXTRA"; fi

echo $DB_JDBC_URL_TEMPLATE;
export DB_JDBC_URL=${DB_JDBC_URL:-${DB_JDBC_URL_TEMPLATE}}

echo $FLYWAY_EXTRA
# Should we update the database?
if [ -n "${UPDATE_DB}" ]; then
	echo "Waiting for database to initialize..."
	sleep 120
	echo "Migrating database with flyway..."
	flyway migrate -url="${DB_JDBC_URL}" -locations=filesystem:${DB_SQLDIR} ${FLYWAY_EXTRA}
fi

catalina.sh run
